name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Install gox
        run: go install github.com/mitchellh/gox@latest

      - name: Install ghr
        run: go install github.com/tcnksm/ghr@latest

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: TAG=${GITHUB_REF#refs/tags/} make release

      - name: Calculate SHA256 checksums
        id: checksums
        run: |
          SHA256=$(sha256sum build/pkg/fargate-td_darwin_amd64.zip | awk '{print $1}')
          SHA256ARM=$(sha256sum build/pkg/fargate-td_darwin_arm64.zip | awk '{print $1}')
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT
          echo "sha256arm=$SHA256ARM" >> $GITHUB_OUTPUT

      - name: Update Homebrew formula
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
          TAG: ${{ github.ref_name }}
          SHA256: ${{ steps.checksums.outputs.sha256 }}
          SHA256ARM: ${{ steps.checksums.outputs.sha256arm }}
        run: make homebrew-release